package PvZ2.APproject.client;

public enum MessageType {
    TEST,
    ERROR,
    OK,

    LOGIN,
    REGISTER,
    LOGOUT,
    SET_SECURITY_QUESTION, FORGOT_PASSWORD, VERIFY_SECURITY_ANSWER, RESET_PASSWORD,
    SYNC_USER_STATE,

    GET_PROFILE,
    UPDATE_PROFILE,

    FIND_PLAYER,
    FIND_RANDOM_MATCH,
    ACCEPT_MATCH,
    REJECT_MATCH,
    MATCH_FOUND,
    MATCH_INVITATION,

    GAME_ACTION,
    GAME_STATE,
    GAME_OVER,

    SEND_REACTION,
    REACTION_RECEIVED,
    GET_LEADERBOARD,
    SUBMIT_SCORE
}
